# Language/versions
language: node_js
node_js:
  - "lts/*"
  - "14"
  - "16"

# Notifications
notifications:
 email:
   - notify+mail@tedeh.net

after_success:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls
